In [1]:
import pandas as pd

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [3]:
df = pd.read_csv('census.csv')

In [4]:
# Set to display all the columns
pd.set_option("display.max_columns", None)

In [5]:
df

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45217,33,Private,Bachelors,13.0,Never-married,Prof-specialty,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
45218,39,Private,Bachelors,13.0,Divorced,Prof-specialty,Not-in-family,White,Female,0.0,0.0,36.0,United-States,<=50K
45219,38,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
45220,44,Private,Bachelors,13.0,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455.0,0.0,40.0,United-States,<=50K
45221,35,Self-emp-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,60.0,United-States,>50K

In [6]:
# Set to display all the rows
pd.set_option("display.max_rows", None)

In [7]:
df.head(50)

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
5,37,Private,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,<=50K
6,49,Private,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K
7,52,Self-emp-not-inc,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K
8,31,Private,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,0.0,50.0,United-States,>50K
9,42,Private,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,0.0,40.0,United-States,>50K
10,37,Private,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,0.0,80.0,United-States,>50K
11,30,State-gov,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
12,23,Private,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
13,32,Private,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,0.0,50.0,United-States,<=50K
14,34,Private,7th-8th,4.0,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0.0,0.0,45.0,Mexico,<=50K
15,25,Self-emp-not-inc,HS-grad,9.0,Never-married,Farming-fishing,Own-child,White,Male,0.0,0.0,35.0,United-States,<=50K
16,32,Private,HS-grad,9.0,Never-married,Machine-op-inspct,Unmarried,White,Male,0.0,0.0,40.0,United-States,<=50K
17,38,Private,11th,7.0,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
18,43,Self-emp-not-inc,Masters,14.0,Divorced,Exec-managerial,Unmarried,White,Female,0.0,0.0,45.0,United-States,>50K
19,40,Private,Doctorate,16.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,60.0,United-States,>50K
20,54,Private,HS-grad,9.0,Separated,Other-service,Unmarried,Black,Female,0.0,0.0,20.0,United-States,<=50K
21,35,Federal-gov,9th,5.0,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
22,43,Private,11th,7.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,2042.0,40.0,United-States,<=50K
23,59,Private,HS-grad,9.0,Divorced,Tech-support,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
24,56,Local-gov,Bachelors,13.0,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
25,19,Private,HS-grad,9.0,Never-married,Craft-repair,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
26,39,Private,HS-grad,9.0,Divorced,Exec-managerial,Not-in-family,White,Male,0.0,0.0,80.0,United-States,<=50K
27,49,Private,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
28,23,Local-gov,Assoc-acdm,12.0,Never-married,Protective-serv,Not-in-family,White,Male,0.0,0.0,52.0,United-States,<=50K
29,20,Private,Some-college,10.0,Never-married,Sales,Own-child,Black,Male,0.0,0.0,44.0,United-States,<=50K
30,45,Private,Bachelors,13.0,Divorced,Exec-managerial,Own-child,White,Male,0.0,1408.0,40.0,United-States,<=50K
31,30,Federal-gov,Some-college,10.0,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
32,22,State-gov,Some-college,10.0,Married-civ-spouse,Other-service,Husband,Black,Male,0.0,0.0,15.0,United-States,<=50K
33,48,Private,11th,7.0,Never-married,Machine-op-inspct,Unmarried,White,Male,0.0,0.0,40.0,Puerto-Rico,<=50K
34,21,Private,Some-college,10.0,Never-married,Machine-op-inspct,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
35,19,Private,HS-grad,9.0,Married-AF-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,25.0,United-States,<=50K
36,48,Self-emp-not-inc,Assoc-acdm,12.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
37,31,Private,9th,5.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,43.0,United-States,<=50K
38,53,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
39,24,Private,Bachelors,13.0,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
40,49,Private,HS-grad,9.0,Separated,Adm-clerical,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
41,25,Private,HS-grad,9.0,Never-married,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,35.0,United-States,<=50K
42,57,Federal-gov,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0.0,0.0,40.0,United-States,>50K
43,53,Private,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,38.0,United-States,<=50K
44,44,Private,Masters,14.0,Divorced,Exec-managerial,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
45,41,State-gov,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
46,29,Private,Assoc-voc,11.0,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,43.0,United-States,<=50K
47,25,Private,Some-college,10.0,Married-civ-spouse,Exec-managerial,Wife,Other,Female,0.0,0.0,40.0,United-States,<=50K
48,47,Private,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Wife,White,Female,0.0,1902.0,60.0,Honduras,>50K
49,50,Federal-gov,Bachelors,13.0,Divorced,Exec-managerial,Not-in-family,White,Male,0.0,0.0,55.0,United-States,>50K

In [8]:
# Set to display all the rows
pd.set_option("display.max_rows", 30)

In [9]:
df.head(20)

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
5,37,Private,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,<=50K
6,49,Private,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K
7,52,Self-emp-not-inc,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K
8,31,Private,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,0.0,50.0,United-States,>50K
9,42,Private,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,0.0,40.0,United-States,>50K
10,37,Private,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,0.0,80.0,United-States,>50K
11,30,State-gov,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
12,23,Private,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
13,32,Private,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,0.0,50.0,United-States,<=50K
14,34,Private,7th-8th,4.0,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0.0,0.0,45.0,Mexico,<=50K
15,25,Self-emp-not-inc,HS-grad,9.0,Never-married,Farming-fishing,Own-child,White,Male,0.0,0.0,35.0,United-States,<=50K
16,32,Private,HS-grad,9.0,Never-married,Machine-op-inspct,Unmarried,White,Male,0.0,0.0,40.0,United-States,<=50K
17,38,Private,11th,7.0,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
18,43,Self-emp-not-inc,Masters,14.0,Divorced,Exec-managerial,Unmarried,White,Female,0.0,0.0,45.0,United-States,>50K
19,40,Private,Doctorate,16.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,60.0,United-States,>50K

In [10]:
df.head(40)

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,19,Private,HS-grad,9.0,Married-AF-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,25.0,United-States,<=50K
36,48,Self-emp-not-inc,Assoc-acdm,12.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
37,31,Private,9th,5.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,43.0,United-States,<=50K
38,53,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
39,24,Private,Bachelors,13.0,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K